// <auto-generated />
using System;
using EasyClaimsCore.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EasyClaimsCore.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250903073847_FixAPIRequestsSeeding")]
    partial class FixAPIRequestsSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EasyClaimsCore.API.Data.Entities.APIRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CipherKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HospitalCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HospitalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("MethodName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("HospitalCode");

                    b.HasIndex("HospitalId");

                    b.HasIndex("HospitalId", "MethodName")
                        .IsUnique();

                    b.ToTable("APIRequests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CipherKey = "PHilheaLthDuMmy311630",
                            HospitalCode = "311630",
                            HospitalId = "H92006568",
                            IsActive = true,
                            MethodName = "GetRestToken"
                        },
                        new
                        {
                            Id = 2,
                            CipherKey = "PHilheaLthDuMmy311630",
                            HospitalCode = "311630",
                            HospitalId = "H92006568",
                            IsActive = true,
                            MethodName = "GetRestMemberPIN"
                        },
                        new
                        {
                            Id = 3,
                            CipherKey = "PHilheaLthDuMmy311630",
                            HospitalCode = "311630",
                            HospitalId = "H92006568",
                            IsActive = true,
                            MethodName = "SearchRestCaseRate"
                        },
                        new
                        {
                            Id = 4,
                            CipherKey = "PHilheaLthDuMmy311630",
                            HospitalCode = "311630",
                            HospitalId = "H92006568",
                            IsActive = true,
                            MethodName = "SearchServerDateTime"
                        },
                        new
                        {
                            Id = 5,
                            CipherKey = "PHilheaLthDuMmy311630",
                            HospitalCode = "311630",
                            HospitalId = "H92006568",
                            IsActive = true,
                            MethodName = "SearchDatabaseDateTime"
                        },
                        new
                        {
                            Id = 6,
                            CipherKey = "PHilheaLthDuMmy311630",
                            HospitalCode = "311630",
                            HospitalId = "H92006568",
                            IsActive = true,
                            MethodName = "GetRestDoctorPAN"
                        },
                        new
                        {
                            Id = 7,
                            CipherKey = "PHilheaLthDuMmy311630",
                            HospitalCode = "311630",
                            HospitalId = "H92006568",
                            IsActive = true,
                            MethodName = "CheckDoctorIfAccredited"
                        },
                        new
                        {
                            Id = 8,
                            CipherKey = "PHilheaLthDuMmy311630",
                            HospitalCode = "311630",
                            HospitalId = "H92006568",
                            IsActive = true,
                            MethodName = "FetchServerVersion"
                        },
                        new
                        {
                            Id = 9,
                            CipherKey = "PHilheaLthDuMmy311630",
                            HospitalCode = "311630",
                            HospitalId = "H92006568",
                            IsActive = true,
                            MethodName = "FindEmployer"
                        },
                        new
                        {
                            Id = 10,
                            CipherKey = "PHilheaLthDuMmy311630",
                            HospitalCode = "311630",
                            HospitalId = "H92006568",
                            IsActive = true,
                            MethodName = "FetchUploadedClaimsMap"
                        },
                        new
                        {
                            Id = 11,
                            CipherKey = "PHilheaLthDuMmy311630",
                            HospitalCode = "311630",
                            HospitalId = "H92006568",
                            IsActive = true,
                            MethodName = "FetchClaimStatus"
                        },
                        new
                        {
                            Id = 12,
                            CipherKey = "PHilheaLthDuMmy311630",
                            HospitalCode = "311630",
                            HospitalId = "H92006568",
                            IsActive = true,
                            MethodName = "isClaimEligibleAPI"
                        },
                        new
                        {
                            Id = 13,
                            CipherKey = "PHilheaLthDuMmy311630",
                            HospitalCode = "311630",
                            HospitalId = "H92006568",
                            IsActive = true,
                            MethodName = "eClaimsFileCheckAPI"
                        },
                        new
                        {
                            Id = 14,
                            CipherKey = "PHilheaLthDuMmy311630",
                            HospitalCode = "311630",
                            HospitalId = "H92006568",
                            IsActive = true,
                            MethodName = "isEsoaValidAPI"
                        },
                        new
                        {
                            Id = 15,
                            CipherKey = "PHilheaLthDuMmy311630",
                            HospitalCode = "311630",
                            HospitalId = "H92006568",
                            IsActive = true,
                            MethodName = "addRequiredApiDocument"
                        },
                        new
                        {
                            Id = 16,
                            CipherKey = "PHilheaLthDuMmy311630",
                            HospitalCode = "311630",
                            HospitalId = "H92006568",
                            IsActive = true,
                            MethodName = "MockResponseAPI"
                        },
                        new
                        {
                            Id = 17,
                            CipherKey = "PHilheaLthDuMmy311630",
                            HospitalCode = "311630",
                            HospitalId = "H92006568",
                            IsActive = true,
                            MethodName = "generatePBEFPDF"
                        },
                        new
                        {
                            Id = 18,
                            CipherKey = "PHilheaLthDuMmy311630",
                            HospitalCode = "311630",
                            HospitalId = "H92006568",
                            IsActive = true,
                            MethodName = "eClaimsApiUpload"
                        },
                        new
                        {
                            Id = 19,
                            CipherKey = "PHilheaLthDuMmy311630",
                            HospitalCode = "311630",
                            HospitalId = "H92006568",
                            IsActive = true,
                            MethodName = "FetchVoucherDetails"
                        },
                        new
                        {
                            Id = 20,
                            CipherKey = "PHilheaLthDuMmy311630",
                            HospitalCode = "311630",
                            HospitalId = "H92006568",
                            IsActive = true,
                            MethodName = "isDRGValidAPI"
                        },
                        new
                        {
                            Id = 21,
                            CipherKey = "PHilheaLthDuMmy311630",
                            HospitalCode = "311630",
                            HospitalId = "H92006568",
                            IsActive = true,
                            MethodName = "MockDecryptResponseAPI"
                        },
                        new
                        {
                            Id = 22,
                            CipherKey = "PHilheaLthDuMmy311630",
                            HospitalCode = "311630",
                            HospitalId = "H92006568",
                            IsActive = true,
                            MethodName = "MockEncryptResponseAPI"
                        });
                });

            modelBuilder.Entity("EasyClaimsCore.API.Data.Entities.APIRequestLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("APIRequestId")
                        .HasColumnType("int");

                    b.Property<int>("ChargeableItems")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RequestData")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Requested")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Responded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Response")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Requested");

                    b.HasIndex("Status");

                    b.HasIndex("APIRequestId", "Requested");

                    b.ToTable("APIRequestLogs");
                });

            modelBuilder.Entity("EasyClaimsCore.API.Data.Entities.APIRequestSuccessLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("APIRequestId")
                        .HasColumnType("int");

                    b.Property<int>("BillAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(10);

                    b.Property<int>("ChargeableItems")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsBilled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Pmcc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RequestData")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Requested")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Responded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Response")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsBilled");

                    b.HasIndex("Pmcc");

                    b.HasIndex("Requested");

                    b.HasIndex("Status");

                    b.HasIndex("APIRequestId", "Requested");

                    b.HasIndex("Pmcc", "IsBilled");

                    b.ToTable("APIRequestSuccessLogs");
                });

            modelBuilder.Entity("EasyClaimsCore.API.Data.Entities.BillAmountParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.ToTable("BillAmountParameters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Price = 10
                        });
                });

            modelBuilder.Entity("EasyClaimsCore.API.Data.Entities.APIRequestLog", b =>
                {
                    b.HasOne("EasyClaimsCore.API.Data.Entities.APIRequest", "APIRequest")
                        .WithMany("APIRequestLogs")
                        .HasForeignKey("APIRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("APIRequest");
                });

            modelBuilder.Entity("EasyClaimsCore.API.Data.Entities.APIRequestSuccessLog", b =>
                {
                    b.HasOne("EasyClaimsCore.API.Data.Entities.APIRequest", "APIRequest")
                        .WithMany()
                        .HasForeignKey("APIRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("APIRequest");
                });

            modelBuilder.Entity("EasyClaimsCore.API.Data.Entities.APIRequest", b =>
                {
                    b.Navigation("APIRequestLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
